// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	baz "github.com/Marcos30004347/kubernetes-posts/pkg/apis/baz"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Bar)(nil), (*baz.Bar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Bar_To_baz_Bar(a.(*Bar), b.(*baz.Bar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*baz.Bar)(nil), (*Bar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_baz_Bar_To_v1alpha1_Bar(a.(*baz.Bar), b.(*Bar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BarList)(nil), (*baz.BarList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BarList_To_baz_BarList(a.(*BarList), b.(*baz.BarList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*baz.BarList)(nil), (*BarList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_baz_BarList_To_v1alpha1_BarList(a.(*baz.BarList), b.(*BarList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BarSpec)(nil), (*baz.BarSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BarSpec_To_baz_BarSpec(a.(*BarSpec), b.(*baz.BarSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*baz.BarSpec)(nil), (*BarSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_baz_BarSpec_To_v1alpha1_BarSpec(a.(*baz.BarSpec), b.(*BarSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Foo)(nil), (*baz.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Foo_To_baz_Foo(a.(*Foo), b.(*baz.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*baz.Foo)(nil), (*Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_baz_Foo_To_v1alpha1_Foo(a.(*baz.Foo), b.(*Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooList)(nil), (*baz.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FooList_To_baz_FooList(a.(*FooList), b.(*baz.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*baz.FooList)(nil), (*FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_baz_FooList_To_v1alpha1_FooList(a.(*baz.FooList), b.(*FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*baz.FooSpec)(nil), (*FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_baz_FooSpec_To_v1alpha1_FooSpec(a.(*baz.FooSpec), b.(*FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*FooSpec)(nil), (*baz.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FooSpec_To_baz_FooSpec(a.(*FooSpec), b.(*baz.FooSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Bar_To_baz_Bar(in *Bar, out *baz.Bar, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BarSpec_To_baz_BarSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Bar_To_baz_Bar is an autogenerated conversion function.
func Convert_v1alpha1_Bar_To_baz_Bar(in *Bar, out *baz.Bar, s conversion.Scope) error {
	return autoConvert_v1alpha1_Bar_To_baz_Bar(in, out, s)
}

func autoConvert_baz_Bar_To_v1alpha1_Bar(in *baz.Bar, out *Bar, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_baz_BarSpec_To_v1alpha1_BarSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_baz_Bar_To_v1alpha1_Bar is an autogenerated conversion function.
func Convert_baz_Bar_To_v1alpha1_Bar(in *baz.Bar, out *Bar, s conversion.Scope) error {
	return autoConvert_baz_Bar_To_v1alpha1_Bar(in, out, s)
}

func autoConvert_v1alpha1_BarList_To_baz_BarList(in *BarList, out *baz.BarList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]baz.Bar)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BarList_To_baz_BarList is an autogenerated conversion function.
func Convert_v1alpha1_BarList_To_baz_BarList(in *BarList, out *baz.BarList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BarList_To_baz_BarList(in, out, s)
}

func autoConvert_baz_BarList_To_v1alpha1_BarList(in *baz.BarList, out *BarList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Bar)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_baz_BarList_To_v1alpha1_BarList is an autogenerated conversion function.
func Convert_baz_BarList_To_v1alpha1_BarList(in *baz.BarList, out *BarList, s conversion.Scope) error {
	return autoConvert_baz_BarList_To_v1alpha1_BarList(in, out, s)
}

func autoConvert_v1alpha1_BarSpec_To_baz_BarSpec(in *BarSpec, out *baz.BarSpec, s conversion.Scope) error {
	out.Description = in.Description
	return nil
}

// Convert_v1alpha1_BarSpec_To_baz_BarSpec is an autogenerated conversion function.
func Convert_v1alpha1_BarSpec_To_baz_BarSpec(in *BarSpec, out *baz.BarSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_BarSpec_To_baz_BarSpec(in, out, s)
}

func autoConvert_baz_BarSpec_To_v1alpha1_BarSpec(in *baz.BarSpec, out *BarSpec, s conversion.Scope) error {
	out.Description = in.Description
	return nil
}

// Convert_baz_BarSpec_To_v1alpha1_BarSpec is an autogenerated conversion function.
func Convert_baz_BarSpec_To_v1alpha1_BarSpec(in *baz.BarSpec, out *BarSpec, s conversion.Scope) error {
	return autoConvert_baz_BarSpec_To_v1alpha1_BarSpec(in, out, s)
}

func autoConvert_v1alpha1_Foo_To_baz_Foo(in *Foo, out *baz.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_FooSpec_To_baz_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Foo_To_baz_Foo is an autogenerated conversion function.
func Convert_v1alpha1_Foo_To_baz_Foo(in *Foo, out *baz.Foo, s conversion.Scope) error {
	return autoConvert_v1alpha1_Foo_To_baz_Foo(in, out, s)
}

func autoConvert_baz_Foo_To_v1alpha1_Foo(in *baz.Foo, out *Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_baz_FooSpec_To_v1alpha1_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_baz_Foo_To_v1alpha1_Foo is an autogenerated conversion function.
func Convert_baz_Foo_To_v1alpha1_Foo(in *baz.Foo, out *Foo, s conversion.Scope) error {
	return autoConvert_baz_Foo_To_v1alpha1_Foo(in, out, s)
}

func autoConvert_v1alpha1_FooList_To_baz_FooList(in *FooList, out *baz.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]baz.Foo, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Foo_To_baz_Foo(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_FooList_To_baz_FooList is an autogenerated conversion function.
func Convert_v1alpha1_FooList_To_baz_FooList(in *FooList, out *baz.FooList, s conversion.Scope) error {
	return autoConvert_v1alpha1_FooList_To_baz_FooList(in, out, s)
}

func autoConvert_baz_FooList_To_v1alpha1_FooList(in *baz.FooList, out *FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Foo, len(*in))
		for i := range *in {
			if err := Convert_baz_Foo_To_v1alpha1_Foo(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_baz_FooList_To_v1alpha1_FooList is an autogenerated conversion function.
func Convert_baz_FooList_To_v1alpha1_FooList(in *baz.FooList, out *FooList, s conversion.Scope) error {
	return autoConvert_baz_FooList_To_v1alpha1_FooList(in, out, s)
}

func autoConvert_v1alpha1_FooSpec_To_baz_FooSpec(in *FooSpec, out *baz.FooSpec, s conversion.Scope) error {
	// INFO: in.Bar opted out of conversion generation
	return nil
}

func autoConvert_baz_FooSpec_To_v1alpha1_FooSpec(in *baz.FooSpec, out *FooSpec, s conversion.Scope) error {
	// INFO: in.Bar opted out of conversion generation
	return nil
}
