apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.baz
spec:
  insecureSkipTLSVerify: true
  group: baz
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: apiserver
    namespace: baz-api
  version: v1alpha1
